# Generated by Django 4.1.1 on 2022-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreintroduction', models.CharField(max_length=200, unique=True)),
                ('descriptionintroduction', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
