# Generated by Django 4.1.1 on 2022-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='titreintroduction',
            field=models.CharField(max_length=200),
        ),
    ]
