# Generated by Django 4.1.1 on 2022-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_alter_introduction_titreintroduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
