# Generated by Django 4.1.1 on 2022-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0003_alter_introduction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='date',
            field=models.DateField(),
        ),
    ]
